### ISSUE TITLE
Recursive file adding does not work

### ISSUE THREAD

**Issue by marius-wieschollek** [AntumDeluge/debreate#8] opened 2016-12-22 21:39 UTC
Python version: 2.7.12
wx.Python version: 3.0.2
Debreate version: 0.7.12
Platform: Ubuntu 14/16 LTS

In debreate 0.7.10 you could add all the files of a folder recursively to your package on the files page and the folder structure was kept. Now it adds all files to the same folder and ignores the structure.

Step to reproduce
1. Create new project
2. Go to "files" page
3. Select a folder with subfolders from your computer
4. Click the "add" button

Expected behaviour
All files are added with the original folder structure as in the selected folder

Actual behaviour
All files are added to the "Target" folder and the folder structure is ignored

**Comment by AntumDeluge** [comment] 2016-12-23 11:41
Thank you for reporting this. It has been fixed in commit 9eb138a.

I will leave this report open for the time being in case of errors in the new code.

**Comment by AntumDeluge** [comment] 2017-01-13 02:47
[0.7.13 released](../releases/tag/v0.7.13).

**Closed by AntumDeluge** 2017-01-13 02:47 UTC

**Comment by brnW** [comment] 2017-01-19 19:28
The folder structure is still ignored with 0.7.13 release.

**Comment by AntumDeluge** [comment] 2017-01-19 21:26
@brnW Could you please explain the steps you are taking to add directories, & the resulting output. I am unable to reproduce the issue. It works for me as expected.

**Comment by brnW** [comment] 2017-01-20 10:33
CPU :   x86_64 (64-bit PAE) 
System :   Linux Mint 18.1  
Python :  2.7.12
wxPython : 3.0.2
Debreate : 0.7.13

1. Open Debreate
2. Go to "File" page
3. Browse to the main project folder on your computer
4. Then select the /usr folder (with subfolders)
5. Select "Custom"
6. Write /usr on the custom field 
7. Click the "add" button

Expected behaviour (like 0.7.10 release) : all files are added with the original folder structure as in /usr (for example /usr/bin/mycommand --->  mycommand in /usr/bin)

Actual behaviour (0.7.13) : only "usr" folder is added to /usr target (that is /usr/usr) and the structure is ignored.

If you select all the tree, each file or folder is added in /usr target. 
Thanks for this work !

**Comment by AntumDeluge** [comment] 2017-01-20 11:25
Okay, if I understand correctly, this issue is different than the original topic.

When adding the directory "*usr*" to the file list, the directory structure is preserved. It's just that the top-level directory "*usr*" is not trimmed from the file path names.

So, let's say the added directory "*usr*" contains the file path "*usr/bin/foo*" and "*usr/share/bar*":
<pre>
usr -- bin -- foo
   |
    -- share -- bar
</pre>

Setting the target directory to "*/usr*" and adding the directory results in the file paths being "*/usr/usr/bin/foo*" and "*/usr/usr/share/bar*". Whereas in 0.7.10, if I remember correctly, they would have been "*/usr/bin/foo*" and "*/usr/share/bar*".

I understand how this could be frustrating. It sounds to me that the answer would be to have an option to preserve the parent directory from all file path names, like the following, so that both behaviors are supported:

![treeopts](https://cloud.githubusercontent.com/assets/3631473/22147818/66614d1e-debf-11e6-95b4-7f4e5f8f73dc.png)

Leaving "*Preserve top-level directories*" unchecked would have the behavior of 0.7.10.

**Comment by AntumDeluge** [comment] 2017-01-20 17:10
Option to preserve top-level directories added. See issue #10
